---
layout: cv
---

# Jacob McEwan
Computer Information Technology

[jacob352mc@gmail.com](mailto:jacob352mc@gmail.com)

## Education

- **Bachelor's in Computer Information Technology (Expected Graduation: December 2024)**  
  Brigham Young University Idaho

## Experience

- **Palermo Villa, IT Intern**  
  Palermo Villa  
  - Provided day to day technical support for all staff, troubleshooting hardware, software, and network issues. Managed user accounts and permissions, cloud services, IT systems, and hardware inventory. Created and updated existing documentation for systems and processes. Supported and contributed to IT projects and their deployments.

- **Sales Clerk, Self-Checkout Attendant**  
  Piggly Wiggly  
  - Monitored, provided support, and taught new employees the cash register and self-checkout systems to streamline both customer and employee experience.

- **Sales Clerk**  
  Kroger  
  - Managed cash register and delivered customer service using point-of-sale, inventory management, and digital payment systems.

## Skills

- Proficient with different forms of technology
- Familiar with JavaScript, Java, HTML, Python, C, SQL, database design, management, and administration, networking and network design, Google Cloud, AWS, software testing, various operating systems, and a strong aptitude for learning new technologies.


<!-- ### Footer

Last updated: May 2013 test1 -->